### ISSUE TITLE
HTTPS Redirect not working on Nginx

### ISSUE THREAD

**Issue by tathspts** [virtualmin/virtualmin-nginx#6]
I am using LEMP stack with Virtual which I installed using "_--bundle LEMP_" while installing virtualmin on a debian9 OS.

When I below settings, The https redirect is not working on any of the domains.

System Settings --> Virtualmin Configurations --> SSL Settings --> Redirect all http to https by default --> yes

However I am able to do the redirect by adding below code in domain.com.conf

server {
        server_name domain.com www.domain.com;
        listen ipaddress:80;
        rewrite ^/(.*) https://domain.com/$1 permanent;
}

But I wonder why the inbuilt feature that ships with virtualmin is not working?

Please note I am using Lets' Encrypt SSL.

on other note I wonder what type of Redirect Virtualmin does if that feature is to work? Is it also 301 redirect?

Any help on this would be immensely helpful. 

Thanks

**Comment by jcameron** [comment]
Doesn't this only work if you have a separate `server` block for SSL and non-SSL though? Otherwise there would be an infinite redirect.

Unfortunately Virtualmin currently only uses a single `server` block for both protocols (unlike Apache).

**Comment by pixel-paul** [comment]
I have recently run into a similiar issue, where we needed to redirect www. to non-www. 

Nginx expects something similar to this to deal with this scenario:

```
server {
    	server_name www.example.com;
	listen 443 ssl http2;
	ssl_certificate /etc/ssl/virtualmin/16848264071884359/ssl.cert;
	ssl_certificate_key /etc/ssl/virtualmin/16848264071884359/ssl.key;
    	return 301 $scheme://example.com$request_uri;
    }

server {
		server_name example.com;
		listen 443;
                ssl_certificate /etc/ssl/virtualmin/16848264071884359/ssl.cert;
	        ssl_certificate_key /etc/ssl/virtualmin/16848264071884359/ssl.key;
                ......
      }
```

**Comment by jcameron** [comment]
The latest version of Virtualmin does support different redirects for HTTP and HTTPS, which you can create in the UI.

**Comment by pixel-paul** [comment]
I did try and use the UI to create this `www.example.com` --> `example.com` redirect, but I couldn't figure it out:

![image](https://github.com/virtualmin/virtualmin-nginx/assets/389303/5e3d75f1-c164-4eec-8572-f08735d7eea9)

The above errors with:

`Failed to save redirect : Missing or invalid source URL path`

Which makes sense of course, as this is a redirect based upon the source path relative to the virtual server domain.

**Comment by jcameron** [comment]
The source URL path should be just `/`

**Comment by pixel-paul** [comment]
I have tried this and I still get the `Failed to save redirect : Missing or invalid source URL path` error

![image](https://github.com/virtualmin/virtualmin-nginx/assets/389303/2c4af28b-2ddc-47e9-ac31-77c02c798f12)

**Comment by jcameron** [comment]
Are you sure there's not a space at the start or end of the path?

**Comment by jcameron** [comment]
Hmm, this is very confusing. Can you check which version of Virtualmin and the Nginx plugin you're running there?

**Comment by pixel-paul** [comment]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Rocky Linux 9.2     |
|  Webmin version      |     2.021      |
|  Usermin version     |     1.861     |
|  Virtualmin version  |     7.7       |
|  Theme version       |     20.21      |
|  Package updates     |     All installed packages are up to date   |

**Comment by jcameron** [comment]
We just released Webmin 2.100 - try upgrading and see if that helps.

**Comment by pixel-paul** [comment]
We're still seeing the same issue with `2.101`:

![image](https://github.com/virtualmin/virtualmin-nginx/assets/389303/1247bff6-1eb8-456a-947c-0c4112f5ee17)

![image](https://github.com/virtualmin/virtualmin-nginx/assets/389303/46a3470a-3686-4b5f-b747-6e5ab3962ae6)

**Comment by iliajie** [comment]
Next Virtualmin release will have it displayed more explicitly using placeholders, e.g.:

<img width="1440" alt="image" src="https://github.com/virtualmin/virtualmin-nginx/assets/4426533/0f8f55f1-af49-418f-83b4-378e6f3c0653">

**Comment by pixel-paul** [comment]
Not sure, Jamie suggested trying 2.101

I tried with a sub directory too (so https://www.example.com/test) and I get the same error.

**Comment by iliajie** [comment]
Please look at my screenshot above for reference.

**Comment by pixel-paul** [comment]
This is related to redirecting www.example.com to example.com

So do we not need to use the second option, 'URL at this website'?

**Comment by iliajie** [comment]
> So do we not need to use the second option, 'URL at this website'?

No. Here the example that will work for you right now:

<img width="1179" alt="image" src="https://github.com/virtualmin/virtualmin-nginx/assets/4426533/0c1249f1-0656-47f1-894b-16b3084ed806">

However, we have bugs that needs to be fixed before we finally release new Virtualmin and Virtualmin Nginx module.

**Comment by pixel-paul** [comment]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Rocky Linux 9.3     |
|  Webmin version      |     2.105      |
|  Usermin version     |     2.005     |
|  Virtualmin version  |     7.8.2       |
|  Theme version       |     21.09.5      |
| Nginx module         |  1.20-1 |
|  Package updates     |     All installed packages are up to date   |


This just results in a redirect loop:

![image](https://github.com/virtualmin/virtualmin-nginx/assets/389303/5ea07013-0971-4091-9688-05243f2cbd7f)

**Comment by pixel-paul** [comment]
Nginx really wants two server blocks to handle the www -> non-www redirect:

https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/#server-name-if

https://serverfault.com/a/1139001
